### ISSUE TITLE
File descriptor leak in albatross-console

### ISSUE THREAD

**Issue by reynir** [robur-coop/albatross#198]
I observed in the syslog that I would get more and more EBADF the more clients I connected and disconnected to albatross-console:

```
Nov 20 09:09:13 bark.sorbus.is albatross-console[953]: albatross-console: [ERROR] exception Unix.Unix_error(Unix.EBADF, "check_descriptor", "") while writing
Nov 20 09:09:13 bark.sorbus.is albatross-console[953]: albatross-console: [ERROR] exception Unix.Unix_error(Unix.EBADF, "check_descriptor", "") while writing
Nov 20 09:09:13 bark.sorbus.is albatross-console[953]: albatross-console: [ERROR] exception Unix.Unix_error(Unix.EBADF, "check_descriptor", "") while writing
Nov 20 09:09:13 bark.sorbus.is albatross-console[953]: albatross-console: [ERROR] exception Unix.Unix_error(Unix.EBADF, "check_descriptor", "") while writing
Nov 20 09:09:13 bark.sorbus.is albatross-console[953]: albatross-console: [ERROR] :opam-mirror error while reading Out of memory
```

Likely introduced in https://github.com/robur-coop/albatross/pull/194.

**Comment by hannesm** [comment]
from what I remember, albatross_console only detects that a client disconnected on the next console output (leading to a write to the client/fd) -- here the exception is printed and the fd should then be closed... not sure whether there are any fd being leaked (but of course would be nice to dig deeper here).
